apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: tcp-liveness-readiness
spec:
  containers:
  - name: tcp-liveness-readiness
    image: cnych/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
      path: /healthz
      port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 3
      perioidSeconds: 3
