apiVersion: v1
kind: Service
metadata:
 name: jenkins
 namespace: kube-ops
 labels:
   app: jenkins
spec:
 selector:
   app: jenkins
 type: NodePort
 ports:
 - name: web
   port: 31000
   targetPort: web
   nodePort: 31002
 - name: agent
   port: 31001
   targetPort: agent