apiVersion: v1
kind: Pod
metadata: 
  name: testcm4-pod
spec:
  containers:
  - name: testcm4
    image: busybox
    command: ["/bin/sh", "-c", "cat /home/ubuntu/testcm/redis.conf"]
    volumeMounts: 
    - name: config-volume
      mountPath: /home/ubuntu/testcm
  volumes: 
  - name: config-volume
    configMap:
      name: cm-demo3