apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: hfbpw-sa-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: hfbpw-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: hfbpw-sa-role
  apiGroup: rbac.authorization.k8s.io