apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: hfbpw-rolebinding
  namespace: kube-system
subjects:
- kind: User
  name: hfbpw
  apiGroup: ""
roleRef:
  kind: Role
  name: hfbpw-role
  apiGroup: ""